### ISSUE TITLE
Today button not working

### ISSUE THREAD

**Issue by alexandretok** [rajeshwarpatlolla/ionic-datepicker#300]
The today button doesn't work when I have the option `closeOnSelect: true`.

The callback isn't fired and the calendar just closes. I can see that the today date is highlighted right before the calendar fades.

**Comment by postb99** [comment]
I've fixed it on my fork but not tagged for now. It fact it was a wrong feature :-)

https://github.com/OSAMES/ionic-datepicker/commit/46f5c6fa2969ce096330123735657fdfeda55eec

**Comment by postb99** [comment]
Fixed on my fork, version 1.4.0. bower package name is ionic-datepicker-fork-ionic1

My fork : https://github.com/OSAMES/ionic-datepicker

I wish I could do a pull request but since I changed package name etc I don't know how to handle this.

**Comment by shankari** [comment]
It looks like commits https://github.com/rajeshwarpatlolla/ionic-datepicker/commit/45631a40970ba5136caca04ea34169a329af53a1 and https://github.com/rajeshwarpatlolla/ionic-datepicker/commit/0fb4e662268fc482c1f015f6f1a2522cd583b8bb (currently on master) might have also fixed this? Trying now...

**Comment by shankari** [comment]
Those commits will probably fix the issue, but the distfile has not been rebuilt to include them. I am rebuilding the distfile using gulp. @rajeshwarpatlolla if I submitted a PR with an updated dist file would you be open to merging it?

**Comment by shankari** [comment]
@postb99 I tried your fork and it still doesn't work. See attached gif. I looked at your code https://github.com/OSAMES/ionic-datepicker/blob/master/src/ionic-datepicker.provider.js#L404 and it looks like the callback is not invoked like in https://github.com/rajeshwarpatlolla/ionic-datepicker/commit/45631a40970ba5136caca04ea34169a329af53a1

Any thoughts on how your fork is supposed to work?

![datepicker_today_not_working mov](https://user-images.githubusercontent.com/2423263/62511595-6f973200-b7c9-11e9-874c-81aab920d726.gif)

**Comment by postb99** [comment]
I am not able to work anymore on this project/my fork, I will close my PR and think you can go on with improvement of official project @shankari
